robot:
  artusLite:
    hand_type: 'left'
    robot_connected: true
    communication_method: 'UART' # 'UART' or 'WiFi'
    communication_channel_identifier: '/dev/ttyUSB0' # 'COM*' on windows, '/dev/ttyUSB*' on linux
    start_robot: true
    reset_on_start: 0
    calibrate: false # calibrate the robot joints
    awake: false
    streaming_frequency: 20  # data/seconds
